FROM golang:1.12

RUN mkdir -p /go/src/adjoe.io && \
    curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && \
    chmod +x /usr/local/bin/dep

WORKDIR /go/src/adjoe.io
