FROM adjoe-test/golang-base

ENV GO111MODULE=on

RUN go get github.com/codegangsta/gin && \
    go get github.com/onsi/ginkgo/ginkgo && \
    go get github.com/go-delve/delve/cmd/dlv && \
    go get github.com/onsi/gomega/...

# Set the local PORT environment variable inside the container
ENV PORT 3000